import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ["Poppins", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        forest: {
          50: "hsl(145 25% 96%)",
          100: "hsl(148 25% 92%)",
          200: "hsl(150 28% 82%)",
          300: "hsl(152 32% 65%)",
          400: "hsl(154 40% 45%)",
          500: "hsl(155 50% 30%)",
          600: "hsl(155 55% 22%)",
          700: "hsl(156 58% 15%)",
          800: "hsl(158 62% 10%)",
          900: "hsl(160 65% 6%)",
        },
        ocean: {
          50: "hsl(210 40% 98%)",
          100: "hsl(210 40% 96%)",
          200: "hsl(210 40% 90%)",
          300: "hsl(210 40% 80%)",
          400: "hsl(212 50% 60%)",
          500: "hsl(215 70% 40%)",
          600: "hsl(218 85% 30%)",
          700: "hsl(220 90% 20%)",
          800: "hsl(222 95% 15%)",
          900: "hsl(224 95% 10%)",
        },
        sunset: {
          50: "hsl(25 100% 97%)",
          100: "hsl(25 100% 95%)",
          200: "hsl(25 100% 88%)",
          300: "hsl(25 100% 75%)",
          400: "hsl(25 100% 60%)",
          500: "hsl(30 100% 50%)",
          600: "hsl(35 100% 40%)",
          700: "hsl(40 100% 30%)",
          800: "hsl(45 100% 20%)",
          900: "hsl(50 100% 15%)",
        },
        forest: {
          50: "hsl(145 25% 96%)",
          100: "hsl(148 25% 92%)",
          200: "hsl(150 28% 82%)",
          300: "hsl(152 32% 65%)",
          400: "hsl(154 40% 45%)",
          500: "hsl(155 50% 30%)",
          600: "hsl(155 55% 22%)",
          700: "hsl(156 58% 15%)",
          800: "hsl(158 62% 10%)",
          900: "hsl(160 65% 6%)",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "2xl": "1.5rem",
        "3xl": "2rem",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "slide-in": {
          from: { opacity: "0", transform: "translateX(-20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "slide-in": "slide-in 0.5s ease-out",
        float: "float 6s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
